spring:
  application:
    name: app
  profiles:
    active: dev
  config:
    import:
      - classpath:application-common.yml
      - classpath:application-job1.yml
      - classpath:application-job2.yml


---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:tcp://localhost:9092/E:/local-db/data/batchdb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:


---
spring:
  config:
    activate:
      on-profile: prod